services:
  # База данных PostgreSQL
  postgres:
    image: postgres:17-alpine
    container_name: food_app_db
    environment:
      POSTGRES_DB: food_app
      POSTGRES_USER: food_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U food_user -d food_app']
      interval: 30s
      timeout: 10s
      retries: 3

  # Приложение
  app:
    image: ${FOOD_APP_IMAGE:-food-app:latest}
    container_name: food_app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
      PORT: 3000
      # Добавьте здесь другие переменные окружения
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads

  # Caddy для проксирования и автоматического HTTPS
  caddy:
    image: caddy:2-alpine
    container_name: food_app_caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
