interface Ingredients {
  name: string;
  amount: number;
  amountType: 'гр' | 'мл' | 'шт' | 'по вкусу';
}

interface Recipe {
  id: number;
  name: string;
  calories: number;
  proteins: number;
  fats: number;
  carbohydrates: number;
  ingredients: Ingredients[];
}

export const recipes: Recipe[] = [
  {
    id: 1,
    name: 'Сырники',
    calories: 164,
    proteins: 14,
    fats: 4.6,
    carbohydrates: 16.9,
    ingredients: [
      { name: 'Творог 5%', amount: 720, amountType: 'гр' },
      { name: 'Яйцо', amount: 120, amountType: 'гр' },
      { name: 'Сахар', amount: 80, amountType: 'гр' },
      { name: 'Ванилин', amount: 1, amountType: 'гр' },
      { name: 'Манная крупа', amount: 65, amountType: 'гр' },
    ],
  },
  {
    id: 2,
    name: 'Блины',
    calories: 147,
    proteins: 5.5,
    fats: 3.8,
    carbohydrates: 22,
    ingredients: [
      { name: 'Молоко 3,2%', amount: 1000, amountType: 'мл' },
      { name: 'Яйцо', amount: 120, amountType: 'гр' },
      { name: 'Мука', amount: 380, amountType: 'гр' },
      { name: 'Соль', amount: 0, amountType: 'по вкусу' },
      { name: 'Растительное масло', amount: 10, amountType: 'гр' },
    ],
  },
  {
    id: 3,
    name: 'Омлет',
    calories: 180,
    proteins: 12,
    fats: 15,
    carbohydrates: 2,
    ingredients: [
      { name: 'Яйцо', amount: 120, amountType: 'гр' },
      { name: 'Сливки 18%', amount: 150, amountType: 'мл' },
      { name: 'Соль', amount: 0, amountType: 'по вкусу' },
    ],
  },
  {
    id: 4,
    name: 'Яичница с колбасой и помидорками',
    calories: 220,
    proteins: 15,
    fats: 18,
    carbohydrates: 3,
    ingredients: [
      { name: 'Яйцо', amount: 120, amountType: 'гр' },
      { name: 'Колбаса докторская Никора', amount: 50, amountType: 'гр' },
      { name: 'Томаты черри', amount: 0, amountType: 'по вкусу' },
    ],
  },
  {
    id: 5,
    name: 'Брускетта с помидорами и песто',
    calories: 120,
    proteins: 4,
    fats: 8,
    carbohydrates: 12,
    ingredients: [
      { name: 'Хлеб', amount: 0, amountType: 'по вкусу' },
      { name: 'Томаты', amount: 0, amountType: 'по вкусу' },
      { name: 'Песто', amount: 0, amountType: 'по вкусу' },
      { name: 'Базилик', amount: 0, amountType: 'по вкусу' },
      { name: 'Соль', amount: 0, amountType: 'по вкусу' },
      { name: 'Оливковое масло', amount: 0, amountType: 'по вкусу' },
    ],
  },
  {
    id: 6,
    name: 'Борщ',
    calories: 85,
    proteins: 4,
    fats: 3,
    carbohydrates: 12,
    ingredients: [
      { name: 'Свёкла', amount: 0, amountType: 'по вкусу' },
      { name: 'Лук', amount: 0, amountType: 'по вкусу' },
      { name: 'Чеснок', amount: 0, amountType: 'по вкусу' },
      { name: 'Болгарский перец', amount: 0, amountType: 'по вкусу' },
      { name: 'Морковь', amount: 0, amountType: 'по вкусу' },
      { name: 'Корень сельдерея', amount: 0, amountType: 'по вкусу' },
      { name: 'Капуста', amount: 0, amountType: 'по вкусу' },
      { name: 'Картофель', amount: 0, amountType: 'по вкусу' },
      { name: 'Укроп', amount: 0, amountType: 'по вкусу' },
      { name: 'Томатная паста', amount: 0, amountType: 'по вкусу' },
      { name: 'Уксус', amount: 0, amountType: 'по вкусу' },
      { name: 'Подсолнечное масло', amount: 0, amountType: 'по вкусу' },
      { name: 'Соль', amount: 0, amountType: 'по вкусу' },
      { name: 'Перец молотый', amount: 0, amountType: 'по вкусу' },
      { name: 'Сахар', amount: 0, amountType: 'по вкусу' },
    ],
  },
  {
    id: 7,
    name: 'Чечевичный суп',
    calories: 95,
    proteins: 8,
    fats: 2,
    carbohydrates: 15,
    ingredients: [
      { name: 'Морковь', amount: 0, amountType: 'по вкусу' },
      { name: 'Лук', amount: 0, amountType: 'по вкусу' },
      { name: 'Куриная грудка', amount: 0, amountType: 'по вкусу' },
      { name: 'Картофель', amount: 0, amountType: 'по вкусу' },
      {
        name: 'Красная чечевица со специями Yelli',
        amount: 0,
        amountType: 'по вкусу',
      },
    ],
  },
  {
    id: 8,
    name: 'Солянка',
    calories: 180,
    proteins: 12,
    fats: 14,
    carbohydrates: 8,
    ingredients: [
      { name: 'Колбаса Мираторг Сервелат', amount: 150, amountType: 'гр' },
      { name: 'Ветчина Schinhoffer круглая', amount: 150, amountType: 'гр' },
      { name: 'Сосиски молочные Никора', amount: 0, amountType: 'по вкусу' },
      { name: 'Картофель', amount: 0, amountType: 'по вкусу' },
      { name: 'Морковь', amount: 0, amountType: 'по вкусу' },
      { name: 'Лук', amount: 0, amountType: 'по вкусу' },
      { name: 'Томатная паста', amount: 70, amountType: 'гр' },
      { name: 'Огурцы маринованные', amount: 0, amountType: 'по вкусу' },
      { name: 'Оливки', amount: 120, amountType: 'гр' },
      { name: 'Растительное масло', amount: 5, amountType: 'гр' },
      { name: 'Соль', amount: 0, amountType: 'по вкусу' },
    ],
  },
  {
    id: 9,
    name: 'Удон',
    calories: 320,
    proteins: 25,
    fats: 8,
    carbohydrates: 45,
    ingredients: [
      { name: 'Удон лапша', amount: 0, amountType: 'по вкусу' },
      { name: 'Морковь', amount: 0, amountType: 'по вкусу' },
      { name: 'Болгарский перец', amount: 0, amountType: 'по вкусу' },
      { name: 'Пекинская капуста', amount: 0, amountType: 'по вкусу' },
      { name: 'Соевый соус', amount: 0, amountType: 'по вкусу' },
      { name: 'Куриная грудка', amount: 500, amountType: 'гр' },
    ],
  },
  {
    id: 10,
    name: 'Греча в сметанной заливке',
    calories: 280,
    proteins: 18,
    fats: 12,
    carbohydrates: 25,
    ingredients: [
      { name: 'Греча', amount: 80, amountType: 'гр' },
      { name: 'Вода', amount: 140, amountType: 'мл' },
      { name: 'Куриная грудка', amount: 150, amountType: 'гр' },
      { name: 'Сметана 15%', amount: 0, amountType: 'по вкусу' },
      { name: 'Вода', amount: 100, amountType: 'мл' },
      { name: 'Чеснок', amount: 0, amountType: 'по вкусу' },
      { name: 'Сыр эмменталь', amount: 100, amountType: 'гр' },
      { name: 'Яйцо', amount: 60, amountType: 'гр' },
    ],
  },
  {
    id: 11,
    name: 'Тефтели в сметанном соусе',
    calories: 320,
    proteins: 22,
    fats: 18,
    carbohydrates: 15,
    ingredients: [
      { name: 'Куриная грудка', amount: 500, amountType: 'гр' },
      { name: 'Яйцо', amount: 60, amountType: 'гр' },
      { name: 'Чеснок', amount: 10, amountType: 'гр' },
      { name: 'Панировочные сухари', amount: 13, amountType: 'гр' },
      { name: 'Растительное масло', amount: 20, amountType: 'гр' },
      { name: 'Морковь', amount: 150, amountType: 'гр' },
      { name: 'Болгарский перец', amount: 90, amountType: 'гр' },
      { name: 'Лук', amount: 85, amountType: 'гр' },
      { name: 'Мука', amount: 30, amountType: 'гр' },
      { name: 'Сметана 15%', amount: 190, amountType: 'гр' },
      { name: 'Вода', amount: 200, amountType: 'мл' },
      { name: 'Чеснок', amount: 15, amountType: 'гр' },
      { name: 'Соль', amount: 10, amountType: 'гр' },
    ],
  },
  {
    id: 12,
    name: 'Курица с картошкой',
    calories: 280,
    proteins: 20,
    fats: 12,
    carbohydrates: 22,
    ingredients: [
      { name: 'Лук', amount: 0, amountType: 'по вкусу' },
      { name: 'Картофель', amount: 0, amountType: 'по вкусу' },
      { name: 'Куриная грудка', amount: 150, amountType: 'гр' },
      { name: 'Греческий йогурт', amount: 0, amountType: 'по вкусу' },
      { name: 'Яйцо', amount: 60, amountType: 'гр' },
      { name: 'Сыр эмменталь', amount: 100, amountType: 'гр' },
      { name: 'Чеснок', amount: 0, amountType: 'по вкусу' },
    ],
  },
  {
    id: 13,
    name: 'Паста с грибами и чесноком',
    calories: 420,
    proteins: 15,
    fats: 18,
    carbohydrates: 55,
    ingredients: [
      { name: 'Паста', amount: 450, amountType: 'гр' },
      { name: 'Шампиньоны', amount: 500, amountType: 'гр' },
      { name: 'Чеснок', amount: 0, amountType: 'по вкусу' },
      { name: 'Сливки 18%', amount: 200, amountType: 'мл' },
      { name: 'Соль', amount: 0, amountType: 'по вкусу' },
    ],
  },
  {
    id: 14,
    name: 'Курица тапака',
    calories: 280,
    proteins: 35,
    fats: 15,
    carbohydrates: 8,
    ingredients: [
      { name: 'Курица', amount: 2000, amountType: 'гр' },
      { name: 'Соль', amount: 8.5, amountType: 'гр' },
      { name: 'Черный перец', amount: 5, amountType: 'гр' },
      { name: 'Аджика', amount: 60, amountType: 'гр' },
      { name: 'Томатная паста', amount: 80, amountType: 'гр' },
      { name: 'Лимон', amount: 65, amountType: 'гр' },
      { name: 'Чеснок', amount: 15, amountType: 'гр' },
      { name: 'Растительное масло', amount: 20, amountType: 'гр' },
    ],
  },
  {
    id: 15,
    name: 'Плов',
    calories: 380,
    proteins: 18,
    fats: 12,
    carbohydrates: 55,
    ingredients: [
      { name: 'Растительное масло', amount: 0, amountType: 'по вкусу' },
      { name: 'Лук', amount: 0, amountType: 'по вкусу' },
      { name: 'Морковь', amount: 0, amountType: 'по вкусу' },
      { name: 'Чеснок', amount: 0, amountType: 'по вкусу' },
      { name: 'Рис басмати', amount: 500, amountType: 'гр' },
      { name: 'Специи для плова Waime', amount: 0, amountType: 'по вкусу' },
      { name: 'Куриная грудка', amount: 500, amountType: 'гр' },
    ],
  },
  {
    id: 16,
    name: 'Паста арабьята',
    calories: 380,
    proteins: 12,
    fats: 8,
    carbohydrates: 65,
    ingredients: [
      { name: 'Чеснок', amount: 0, amountType: 'по вкусу' },
      { name: 'Томаты консервированные', amount: 0, amountType: 'по вкусу' },
      { name: 'Базилик', amount: 0, amountType: 'по вкусу' },
      { name: 'Красный перец хлопьями', amount: 0, amountType: 'по вкусу' },
      { name: 'Паста пенне', amount: 450, amountType: 'гр' },
    ],
  },
  {
    id: 17,
    name: 'Пюре картофельное',
    calories: 120,
    proteins: 3,
    fats: 5,
    carbohydrates: 18,
    ingredients: [
      { name: 'Картофель', amount: 1000, amountType: 'гр' },
      { name: 'Молоко', amount: 0, amountType: 'по вкусу' },
      { name: 'Сливочное масло', amount: 0, amountType: 'по вкусу' },
    ],
  },
  {
    id: 18,
    name: 'Рис басмати',
    calories: 130,
    proteins: 3,
    fats: 0.5,
    carbohydrates: 28,
    ingredients: [
      { name: 'Рис', amount: 240, amountType: 'гр' },
      { name: 'Вода', amount: 400, amountType: 'мл' },
      { name: 'Соль', amount: 8, amountType: 'гр' },
    ],
  },
  {
    id: 19,
    name: 'Греча в пакетиках',
    calories: 110,
    proteins: 4,
    fats: 1,
    carbohydrates: 22,
    ingredients: [
      { name: 'Греча', amount: 80, amountType: 'гр' },
      { name: 'Вода', amount: 140, amountType: 'мл' },
      { name: 'Соль', amount: 7, amountType: 'гр' },
    ],
  },
  {
    id: 20,
    name: 'Макароны',
    calories: 130,
    proteins: 5,
    fats: 1,
    carbohydrates: 25,
    ingredients: [
      { name: 'Макароны', amount: 0, amountType: 'по вкусу' },
      { name: 'Вода', amount: 0, amountType: 'по вкусу' },
      { name: 'Соль', amount: 0, amountType: 'по вкусу' },
    ],
  },
  {
    id: 21,
    name: 'Кускус',
    calories: 110,
    proteins: 4,
    fats: 0.5,
    carbohydrates: 23,
    ingredients: [
      { name: 'Кускус', amount: 0, amountType: 'по вкусу' },
      { name: 'Вода', amount: 0, amountType: 'по вкусу' },
      { name: 'Соль', amount: 0, amountType: 'по вкусу' },
    ],
  },
  {
    id: 22,
    name: 'Салат оливье',
    calories: 180,
    proteins: 8,
    fats: 12,
    carbohydrates: 12,
    ingredients: [
      { name: 'Колбаса докторская Никора', amount: 500, amountType: 'гр' },
      { name: 'Яйцо', amount: 0, amountType: 'по вкусу' },
      { name: 'Морковь', amount: 500, amountType: 'гр' },
      { name: 'Картофель', amount: 500, amountType: 'гр' },
      { name: 'Маринованные огурцы', amount: 0, amountType: 'по вкусу' },
      { name: 'Консервированный горошек', amount: 0, amountType: 'по вкусу' },
      { name: 'Майонез', amount: 0, amountType: 'по вкусу' },
    ],
  },
  {
    id: 23,
    name: 'Салат крабовый',
    calories: 150,
    proteins: 6,
    fats: 8,
    carbohydrates: 12,
    ingredients: [
      { name: 'Крабовые палочки', amount: 0, amountType: 'по вкусу' },
      { name: 'Кукуруза консервированная', amount: 0, amountType: 'по вкусу' },
      { name: 'Яйцо отварное', amount: 0, amountType: 'по вкусу' },
      { name: 'Рис', amount: 300, amountType: 'гр' },
      { name: 'Майонез', amount: 0, amountType: 'по вкусу' },
    ],
  },
  {
    id: 24,
    name: 'Салат овощной',
    calories: 45,
    proteins: 2,
    fats: 3,
    carbohydrates: 5,
    ingredients: [
      { name: 'Огурец', amount: 0, amountType: 'по вкусу' },
      { name: 'Томаты черри', amount: 0, amountType: 'по вкусу' },
      { name: 'Болгарский перец', amount: 0, amountType: 'по вкусу' },
      { name: 'Кинза', amount: 0, amountType: 'по вкусу' },
      { name: 'Масло кахетинское', amount: 0, amountType: 'по вкусу' },
      { name: 'Соль', amount: 0, amountType: 'по вкусу' },
    ],
  },
  {
    id: 25,
    name: 'Салат греческий',
    calories: 85,
    proteins: 4,
    fats: 6,
    carbohydrates: 6,
    ingredients: [
      { name: 'Огурец', amount: 0, amountType: 'по вкусу' },
      { name: 'Томаты черри', amount: 0, amountType: 'по вкусу' },
      { name: 'Болгарский перец', amount: 0, amountType: 'по вкусу' },
      { name: 'Маслины', amount: 0, amountType: 'по вкусу' },
      { name: 'Сыр Danish white Emborg', amount: 0, amountType: 'по вкусу' },
      { name: 'Лимонный сок', amount: 0, amountType: 'по вкусу' },
      { name: 'Оливковое масло', amount: 0, amountType: 'по вкусу' },
    ],
  },
];
